version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8888:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    restart: on-failure
    command: >
      sh -c "python run.py runserver 0.0.0.0:8000"
