version: '3.7'
networks:
  meduzzen:
    name: meduzzen
services:
  backend:
    container_name: meduzzen_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    #      - "5555:5555"
    networks:
      - meduzzen
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/fastapi_app
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
      REDIS_URL: "redis://${REDIS_HOST}:${REDIS_PORT}/0"
    restart: on-failure

  redis:
    image: "redis:7-alpine"
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server
    volumes:
      - cache:/data
    restart: on-failure
    networks:
      - meduzzen
    env_file:
      - .env
  postgres:
    container_name: postgres
    image: "postgres:15-alpine"
    env_file:
      - .env
    networks:
      - meduzzen
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_data:
  backend_data:
  cache:
