version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgresql://tamtik:root@postgres:5432/postgres"
      REDIS_URL: "redis://redis:6379/0"
    restart: on-failure

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:latest"
    env_file:
      - .env
    environment:
      POSTGRES_USER: tamtik
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
volumes:
  db:
  cache:
  pgadmin:
