version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${ALLOW_PORT}:${APP_PORT}"
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
      REDIS_URL: "redis://${REDIS_HOST}:${REDIS_PORT}/0"
    restart: on-failure

  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server
    volumes:
      - cache:/data
    restart: on-failure

  postgres:
    image: "postgres:latest"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
volumes:
  db:
  cache:
  pgadmin:
