"""quiz_add_field

Revision ID: 2a3225e6d868
Revises: 374cfac23c6f
Create Date: 2023-09-07 20:36:32.883235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3225e6d868'
down_revision = '374cfac23c6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_table', sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_table', 'is_deleted')
    # ### end Alembic commands ###
