"""init

Revision ID: 5279f3c44eb0
Revises: 
Create Date: 2023-09-13 02:59:16.526161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5279f3c44eb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_company_table_id'), 'company_table', ['id'], unique=False)
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_table_email'), 'user_table', ['email'], unique=True)
    op.create_index(op.f('ix_user_table_id'), 'user_table', ['id'], unique=False)
    op.create_table('employee_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('invitation_status', sa.String(), nullable=True),
    sa.Column('request_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('frequency_in_days', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_table_id'), 'quiz_table', ['id'], unique=False)
    op.create_table('notification_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('massage', sa.String(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_table_id'), 'notification_table', ['id'], unique=False)
    op.create_table('question_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_table_id'), 'question_table', ['id'], unique=False)
    op.create_table('quiz_result_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('total_question', sa.Integer(), nullable=True),
    sa.Column('total_answers', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_table.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_result_table_id'), 'quiz_result_table', ['id'], unique=False)
    op.create_table('answer_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_table_id'), 'answer_table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_table_id'), table_name='answer_table')
    op.drop_table('answer_table')
    op.drop_index(op.f('ix_quiz_result_table_id'), table_name='quiz_result_table')
    op.drop_table('quiz_result_table')
    op.drop_index(op.f('ix_question_table_id'), table_name='question_table')
    op.drop_table('question_table')
    op.drop_index(op.f('ix_notification_table_id'), table_name='notification_table')
    op.drop_table('notification_table')
    op.drop_index(op.f('ix_quiz_table_id'), table_name='quiz_table')
    op.drop_table('quiz_table')
    op.drop_table('employee_table')
    op.drop_index(op.f('ix_user_table_id'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_email'), table_name='user_table')
    op.drop_table('user_table')
    op.drop_index(op.f('ix_company_table_id'), table_name='company_table')
    op.drop_table('company_table')
    # ### end Alembic commands ###
