"""change Employee model

Revision ID: 67d12defff9d
Revises: 9fb75e506ae6
Create Date: 2023-08-16 14:16:00.014929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67d12defff9d'
down_revision = '9fb75e506ae6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_table', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('employee_table', 'request_sent_at')
    op.drop_column('employee_table', 'invitation_sent_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_table', sa.Column('invitation_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('employee_table', sa.Column('request_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('employee_table', 'created_at')
    # ### end Alembic commands ###
