"""quiz_rezult_CASCADE

Revision ID: 85f7d2c4144a
Revises: 76b133c74fc0
Create Date: 2023-09-10 17:37:20.352223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f7d2c4144a'
down_revision = '76b133c74fc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_result_table_user_id_fkey', 'quiz_result_table', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_result_table', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_result_table', type_='foreignkey')
    op.create_foreign_key('quiz_result_table_user_id_fkey', 'quiz_result_table', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###
