"""init

Revision ID: 9fb75e506ae6
Revises: 6dbbe5b3a2a2
Create Date: 2023-08-14 15:05:07.317228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb75e506ae6'
down_revision = '6dbbe5b3a2a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_table', sa.Column('invitation_status', sa.String(), nullable=True))
    op.add_column('employee_table', sa.Column('request_status', sa.String(), nullable=True))
    op.add_column('employee_table', sa.Column('invitation_sent_at', sa.DateTime(), nullable=True))
    op.add_column('employee_table', sa.Column('request_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_table', 'request_sent_at')
    op.drop_column('employee_table', 'invitation_sent_at')
    op.drop_column('employee_table', 'request_status')
    op.drop_column('employee_table', 'invitation_status')
    # ### end Alembic commands ###
